//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public int Id { get; set; }
        public string Purchase { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
